
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'AnandDockerHub'
        repository: 'anand2485/pipeline-test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'




