# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPush
    steps: 
    - task: Docker@2
      inputs:
        containerRegistry: 'AnandDockerHub'
        repository: 'anand2485/node-hello-world'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

